title: Captain Carts
email: byron@byronroark.com
description: >- # this means to ignore newlines until "baseurl:"
  Cricket Golf Carts are collapsible mini golf carts that are perfect for campers
  and RV enthusiasts that want to take a golf cart along for the ride, but don’t 
  have the room for a regular sized one. The Cricket Mini Golf Cart is one of the
  most versatile golf carts in the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://localhost" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed